<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>dce395db-a2d7-4842-b52e-3ffe7194e95b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.1" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.3.1" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="9.3.1-preview.1.25305.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ActivityAPI\ActivityAPI.csproj" />
    <ProjectReference Include="..\APIGateway\APIGateway.csproj" />
    <ProjectReference Include="..\BlogApi\BlogApi.csproj" />
    <ProjectReference Include="..\DatabaseManager\DatabaseManager.csproj" />
    <ProjectReference Include="..\DatabaseSeeder\DatabaseSeeder.csproj" />
    <ProjectReference Include="..\FragmentAPI\FragmentAPI.csproj" />
    <ProjectReference Include="..\TechAPI\TechAPI.csproj" />
    <ProjectReference Include="..\Website\Website\Website.csproj" />
  </ItemGroup>

</Project>
